# 6) 일부 컬럼을 기준으로 데이터 가져오기 Subset Variables (Columns)

In [3]:
import pandas as pd
import seaborn as sns #seaborn은 데이터 시각화 툴이며, anaaconda에 기본적으로 설치 되어있다.

In [37]:
df = sns.load_dataset("iris")
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [11]:
df = df[['sepal_width', 'sepal_length', 'species']] #이 관련된 데이터셋이 iris 데이터에 있어서 seaborn을 불러와야 한다.
df.head()

   sepal_width  sepal_length species
0          3.5           5.1  setosa
1          3.0           4.9  setosa
2          3.2           4.7  setosa
3          3.1           4.6  setosa
4          3.6           5.0  setosa

In [12]:
columns = ['sepal_width', 'sepal_length', 'species']
df[columns]

     sepal_width  sepal_length    species
0            3.5           5.1     setosa
1            3.0           4.9     setosa
2            3.2           4.7     setosa
3            3.1           4.6     setosa
4            3.6           5.0     setosa
5            3.9           5.4     setosa
6            3.4           4.6     setosa
7            3.4           5.0     setosa
8            2.9           4.4     setosa
9            3.1           4.9     setosa
10           3.7           5.4     setosa
11           3.4           4.8     setosa
12           3.0           4.8     setosa
13           3.0           4.3     setosa
14           4.0           5.8     setosa
15           4.4           5.7     setosa
16           3.9           5.4     setosa
17           3.5           5.1     setosa
18           3.8           5.7     setosa
19           3.8           5.1     setosa
20           3.4           5.4     setosa
21           3.7           5.1     setosa
22           3.6           4.6     setosa
23           3.3           5.1     setosa
24           3.4           4.8     setosa
25           3.0           5.0     setosa
26           3.4           5.0     setosa
27           3.5           5.2     setosa
28           3.4           5.2     setosa
29           3.2           4.7     setosa
..           ...           ...        ...
120          3.2           6.9  virginica
121          2.8           5.6  virginica
122          2.8           7.7  virginica
123          2.7           6.3  virginica
124          3.3           6.7  virginica
125          3.2           7.2  virginica
126          2.8           6.2  virginica
127          3.0           6.1  virginica
128          2.8           6.4  virginica
129          3.0           7.2  virginica
130          2.8           7.4  virginica
131          3.8           7.9  virginica
132          2.8           6.4  virginica
133          2.8           6.3  virginica
134          2.6           6.1  virginica
135          3.0           7.7  virginica
136          3.4           6.3  virginica
137          3.1           6.4  virginica
138          3.0           6.0  virginica
139          3.1           6.9  virginica
140          3.1           6.7  virginica
141          3.1           6.9  virginica
142          2.7           5.8  virginica
143          3.2           6.8  virginica
144          3.3           6.7  virginica
145          3.0           6.7  virginica
146          2.5           6.3  virginica
147          3.0           6.5  virginica
148          3.4           6.2  virginica
149          3.0           5.9  virginica

[150 rows x 3 columns]

In [13]:
columns = ['sepal_width', 'sepal_length', 'species']
df['sepal_width'] #하나의 column만 가져오고 싶을 때는 특정 column명만 넣기

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
5      3.9
6      3.4
7      3.4
8      2.9
9      3.1
10     3.7
11     3.4
12     3.0
13     3.0
14     4.0
15     4.4
16     3.9
17     3.5
18     3.8
19     3.8
20     3.4
21     3.7
22     3.6
23     3.3
24     3.4
25     3.0
26     3.4
27     3.5
28     3.4
29     3.2
      ...
120    3.2
121    2.8
122    2.8
123    2.7
124    3.3
125    3.2
126    2.8
127    3.0
128    2.8
129    3.0
130    2.8
131    3.8
132    2.8
133    2.8
134    2.6
135    3.0
136    3.4
137    3.1
138    3.0
139    3.1
140    3.1
141    3.1
142    2.7
143    3.2
144    3.3
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal_width, Length: 150, dtype: float64

In [15]:
df['sepal_width']

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
5      3.9
6      3.4
7      3.4
8      2.9
9      3.1
10     3.7
11     3.4
12     3.0
13     3.0
14     4.0
15     4.4
16     3.9
17     3.5
18     3.8
19     3.8
20     3.4
21     3.7
22     3.6
23     3.3
24     3.4
25     3.0
26     3.4
27     3.5
28     3.4
29     3.2
      ...
120    3.2
121    2.8
122    2.8
123    2.7
124    3.3
125    3.2
126    2.8
127    3.0
128    2.8
129    3.0
130    2.8
131    3.8
132    2.8
133    2.8
134    2.6
135    3.0
136    3.4
137    3.1
138    3.0
139    3.1
140    3.1
141    3.1
142    2.7
143    3.2
144    3.3
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal_width, Length: 150, dtype: float64

In [18]:
df.sepal_width #단 한글인 경우에는 안될 가능성이 있으므로 감싸서 불러오기.

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
5      3.9
6      3.4
7      3.4
8      2.9
9      3.1
10     3.7
11     3.4
12     3.0
13     3.0
14     4.0
15     4.4
16     3.9
17     3.5
18     3.8
19     3.8
20     3.4
21     3.7
22     3.6
23     3.3
24     3.4
25     3.0
26     3.4
27     3.5
28     3.4
29     3.2
      ...
120    3.2
121    2.8
122    2.8
123    2.7
124    3.3
125    3.2
126    2.8
127    3.0
128    2.8
129    3.0
130    2.8
131    3.8
132    2.8
133    2.8
134    2.6
135    3.0
136    3.4
137    3.1
138    3.0
139    3.1
140    3.1
141    3.1
142    2.7
143    3.2
144    3.3
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal_width, Length: 150, dtype: float64

In [19]:
df.filter(regex = 'regex') #regex는 정규표현식을 의미한다. 조건이 없으므로 현재는 index만 가져왔다.

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[150 rows x 0 columns]

In [21]:
df.filter(regex = '\.') #정규표현식에 조건을 달면 '.'이 들어간 column을 가져온다.

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[150 rows x 0 columns]

In [22]:
df.filter(regex = '_') # '_'만 들어간 것 뽑아온다.

     sepal_width  sepal_length
0            3.5           5.1
1            3.0           4.9
2            3.2           4.7
3            3.1           4.6
4            3.6           5.0
5            3.9           5.4
6            3.4           4.6
7            3.4           5.0
8            2.9           4.4
9            3.1           4.9
10           3.7           5.4
11           3.4           4.8
12           3.0           4.8
13           3.0           4.3
14           4.0           5.8
15           4.4           5.7
16           3.9           5.4
17           3.5           5.1
18           3.8           5.7
19           3.8           5.1
20           3.4           5.4
21           3.7           5.1
22           3.6           4.6
23           3.3           5.1
24           3.4           4.8
25           3.0           5.0
26           3.4           5.0
27           3.5           5.2
28           3.4           5.2
29           3.2           4.7
..           ...           ...
120          3.2           6.9
121          2.8           5.6
122          2.8           7.7
123          2.7           6.3
124          3.3           6.7
125          3.2           7.2
126          2.8           6.2
127          3.0           6.1
128          2.8           6.4
129          3.0           7.2
130          2.8           7.4
131          3.8           7.9
132          2.8           6.4
133          2.8           6.3
134          2.6           6.1
135          3.0           7.7
136          3.4           6.3
137          3.1           6.4
138          3.0           6.0
139          3.1           6.9
140          3.1           6.7
141          3.1           6.9
142          2.7           5.8
143          3.2           6.8
144          3.3           6.7
145          3.0           6.7
146          2.5           6.3
147          3.0           6.5
148          3.4           6.2
149          3.0           5.9

[150 rows x 2 columns]

In [26]:
df.filter(regex = 'length$' )

     sepal_length
0             5.1
1             4.9
2             4.7
3             4.6
4             5.0
5             5.4
6             4.6
7             5.0
8             4.4
9             4.9
10            5.4
11            4.8
12            4.8
13            4.3
14            5.8
15            5.7
16            5.4
17            5.1
18            5.7
19            5.1
20            5.4
21            5.1
22            4.6
23            5.1
24            4.8
25            5.0
26            5.0
27            5.2
28            5.2
29            4.7
..            ...
120           6.9
121           5.6
122           7.7
123           6.3
124           6.7
125           7.2
126           6.2
127           6.1
128           6.4
129           7.2
130           7.4
131           7.9
132           6.4
133           6.3
134           6.1
135           7.7
136           6.3
137           6.4
138           6.0
139           6.9
140           6.7
141           6.9
142           5.8
143           6.8
144           6.7
145           6.7
146           6.3
147           6.5
148           6.2
149           5.9

[150 rows x 1 columns]

In [25]:
df.filter(regex = '^sepal') # 특정 문자.대소문자 맞추기

     sepal_width  sepal_length
0            3.5           5.1
1            3.0           4.9
2            3.2           4.7
3            3.1           4.6
4            3.6           5.0
5            3.9           5.4
6            3.4           4.6
7            3.4           5.0
8            2.9           4.4
9            3.1           4.9
10           3.7           5.4
11           3.4           4.8
12           3.0           4.8
13           3.0           4.3
14           4.0           5.8
15           4.4           5.7
16           3.9           5.4
17           3.5           5.1
18           3.8           5.7
19           3.8           5.1
20           3.4           5.4
21           3.7           5.1
22           3.6           4.6
23           3.3           5.1
24           3.4           4.8
25           3.0           5.0
26           3.4           5.0
27           3.5           5.2
28           3.4           5.2
29           3.2           4.7
..           ...           ...
120          3.2           6.9
121          2.8           5.6
122          2.8           7.7
123          2.7           6.3
124          3.3           6.7
125          3.2           7.2
126          2.8           6.2
127          3.0           6.1
128          2.8           6.4
129          3.0           7.2
130          2.8           7.4
131          3.8           7.9
132          2.8           6.4
133          2.8           6.3
134          2.6           6.1
135          3.0           7.7
136          3.4           6.3
137          3.1           6.4
138          3.0           6.0
139          3.1           6.9
140          3.1           6.7
141          3.1           6.9
142          2.7           5.8
143          3.2           6.8
144          3.3           6.7
145          3.0           6.7
146          2.5           6.3
147          3.0           6.5
148          3.4           6.2
149          3.0           5.9

[150 rows x 2 columns]

In [27]:
df.filter(regex = '^x[1-5]$') #'^x[1-5]$' 이런 컬럼이 없으므로 불러오지 않는다. x로시작하고 1-5까지 가져오기

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[150 rows x 0 columns]

In [29]:
df.filter(regex = 'es$') #es로 끝나는거

       species
0       setosa
1       setosa
2       setosa
3       setosa
4       setosa
5       setosa
6       setosa
7       setosa
8       setosa
9       setosa
10      setosa
11      setosa
12      setosa
13      setosa
14      setosa
15      setosa
16      setosa
17      setosa
18      setosa
19      setosa
20      setosa
21      setosa
22      setosa
23      setosa
24      setosa
25      setosa
26      setosa
27      setosa
28      setosa
29      setosa
..         ...
120  virginica
121  virginica
122  virginica
123  virginica
124  virginica
125  virginica
126  virginica
127  virginica
128  virginica
129  virginica
130  virginica
131  virginica
132  virginica
133  virginica
134  virginica
135  virginica
136  virginica
137  virginica
138  virginica
139  virginica
140  virginica
141  virginica
142  virginica
143  virginica
144  virginica
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

[150 rows x 1 columns]

In [31]:
df.filter(regex = '^(?!species$).*') #not을 의미하므로 species 빼고 보여줘

     sepal_width  sepal_length
0            3.5           5.1
1            3.0           4.9
2            3.2           4.7
3            3.1           4.6
4            3.6           5.0
5            3.9           5.4
6            3.4           4.6
7            3.4           5.0
8            2.9           4.4
9            3.1           4.9
10           3.7           5.4
11           3.4           4.8
12           3.0           4.8
13           3.0           4.3
14           4.0           5.8
15           4.4           5.7
16           3.9           5.4
17           3.5           5.1
18           3.8           5.7
19           3.8           5.1
20           3.4           5.4
21           3.7           5.1
22           3.6           4.6
23           3.3           5.1
24           3.4           4.8
25           3.0           5.0
26           3.4           5.0
27           3.5           5.2
28           3.4           5.2
29           3.2           4.7
..           ...           ...
120          3.2           6.9
121          2.8           5.6
122          2.8           7.7
123          2.7           6.3
124          3.3           6.7
125          3.2           7.2
126          2.8           6.2
127          3.0           6.1
128          2.8           6.4
129          3.0           7.2
130          2.8           7.4
131          3.8           7.9
132          2.8           6.4
133          2.8           6.3
134          2.6           6.1
135          3.0           7.7
136          3.4           6.3
137          3.1           6.4
138          3.0           6.0
139          3.1           6.9
140          3.1           6.7
141          3.1           6.9
142          2.7           5.8
143          3.2           6.8
144          3.3           6.7
145          3.0           6.7
146          2.5           6.3
147          3.0           6.5
148          3.4           6.2
149          3.0           5.9

[150 rows x 2 columns]

In [38]:
df.loc[2:5,'sepal_width':'petal_width'] #위에 올려서 df petal column있는걸로 실행 후 이 part 실행하기
#앞에는 행(2:5). 뒤에는 index(column명)으로 indexing 한다고 보면 된다.

   sepal_width  petal_length  petal_width
2          3.2           1.3          0.2
3          3.1           1.5          0.2
4          3.6           1.4          0.2
5          3.9           1.7          0.4

In [41]:
df.iloc[:, [1,2,4]] #loc는 에러난다. iloc로 해야한다. loc는 끝까지 다 가져오는데 iloc는 끝-1까지 가져온다.

     sepal_width  petal_length    species
0            3.5           1.4     setosa
1            3.0           1.4     setosa
2            3.2           1.3     setosa
3            3.1           1.5     setosa
4            3.6           1.4     setosa
5            3.9           1.7     setosa
6            3.4           1.4     setosa
7            3.4           1.5     setosa
8            2.9           1.4     setosa
9            3.1           1.5     setosa
10           3.7           1.5     setosa
11           3.4           1.6     setosa
12           3.0           1.4     setosa
13           3.0           1.1     setosa
14           4.0           1.2     setosa
15           4.4           1.5     setosa
16           3.9           1.3     setosa
17           3.5           1.4     setosa
18           3.8           1.7     setosa
19           3.8           1.5     setosa
20           3.4           1.7     setosa
21           3.7           1.5     setosa
22           3.6           1.0     setosa
23           3.3           1.7     setosa
24           3.4           1.9     setosa
25           3.0           1.6     setosa
26           3.4           1.6     setosa
27           3.5           1.5     setosa
28           3.4           1.4     setosa
29           3.2           1.6     setosa
..           ...           ...        ...
120          3.2           5.7  virginica
121          2.8           4.9  virginica
122          2.8           6.7  virginica
123          2.7           4.9  virginica
124          3.3           5.7  virginica
125          3.2           6.0  virginica
126          2.8           4.8  virginica
127          3.0           4.9  virginica
128          2.8           5.6  virginica
129          3.0           5.8  virginica
130          2.8           6.1  virginica
131          3.8           6.4  virginica
132          2.8           5.6  virginica
133          2.8           5.1  virginica
134          2.6           5.6  virginica
135          3.0           6.1  virginica
136          3.4           5.6  virginica
137          3.1           5.5  virginica
138          3.0           4.8  virginica
139          3.1           5.4  virginica
140          3.1           5.6  virginica
141          3.1           5.1  virginica
142          2.7           5.1  virginica
143          3.2           5.9  virginica
144          3.3           5.7  virginica
145          3.0           5.2  virginica
146          2.5           5.0  virginica
147          3.0           5.2  virginica
148          3.4           5.4  virginica
149          3.0           5.1  virginica

[150 rows x 3 columns]

In [42]:
df.iloc[:, [1,3]]

     sepal_width  petal_width
0            3.5          0.2
1            3.0          0.2
2            3.2          0.2
3            3.1          0.2
4            3.6          0.2
5            3.9          0.4
6            3.4          0.3
7            3.4          0.2
8            2.9          0.2
9            3.1          0.1
10           3.7          0.2
11           3.4          0.2
12           3.0          0.1
13           3.0          0.1
14           4.0          0.2
15           4.4          0.4
16           3.9          0.4
17           3.5          0.3
18           3.8          0.3
19           3.8          0.3
20           3.4          0.2
21           3.7          0.4
22           3.6          0.2
23           3.3          0.5
24           3.4          0.2
25           3.0          0.2
26           3.4          0.4
27           3.5          0.2
28           3.4          0.2
29           3.2          0.2
..           ...          ...
120          3.2          2.3
121          2.8          2.0
122          2.8          2.0
123          2.7          1.8
124          3.3          2.1
125          3.2          1.8
126          2.8          1.8
127          3.0          1.8
128          2.8          2.1
129          3.0          1.6
130          2.8          1.9
131          3.8          2.0
132          2.8          2.2
133          2.8          1.5
134          2.6          1.4
135          3.0          2.3
136          3.4          2.4
137          3.1          1.8
138          3.0          1.8
139          3.1          2.1
140          3.1          2.4
141          3.1          2.3
142          2.7          1.9
143          3.2          2.3
144          3.3          2.5
145          3.0          2.3
146          2.5          1.9
147          3.0          2.0
148          3.4          2.3
149          3.0          1.8

[150 rows x 2 columns]

In [43]:
df.iloc[-5: , [1,3]] #뒤에서 5개까지만 보고싶다.

     sepal_width  petal_width
145          3.0          2.3
146          2.5          1.9
147          3.0          2.0
148          3.4          2.3
149          3.0          1.8

In [46]:
df.loc[df['sepal_length'] > 3, ['sepal_length','sepal_width']] # 3보다 큰 값 불러오기/ 앞에 꺼 행, 뒤에는 열

     sepal_length  sepal_width
0             5.1          3.5
1             4.9          3.0
2             4.7          3.2
3             4.6          3.1
4             5.0          3.6
5             5.4          3.9
6             4.6          3.4
7             5.0          3.4
8             4.4          2.9
9             4.9          3.1
10            5.4          3.7
11            4.8          3.4
12            4.8          3.0
13            4.3          3.0
14            5.8          4.0
15            5.7          4.4
16            5.4          3.9
17            5.1          3.5
18            5.7          3.8
19            5.1          3.8
20            5.4          3.4
21            5.1          3.7
22            4.6          3.6
23            5.1          3.3
24            4.8          3.4
25            5.0          3.0
26            5.0          3.4
27            5.2          3.5
28            5.2          3.4
29            4.7          3.2
..            ...          ...
120           6.9          3.2
121           5.6          2.8
122           7.7          2.8
123           6.3          2.7
124           6.7          3.3
125           7.2          3.2
126           6.2          2.8
127           6.1          3.0
128           6.4          2.8
129           7.2          3.0
130           7.4          2.8
131           7.9          3.8
132           6.4          2.8
133           6.3          2.8
134           6.1          2.6
135           7.7          3.0
136           6.3          3.4
137           6.4          3.1
138           6.0          3.0
139           6.9          3.1
140           6.7          3.1
141           6.9          3.1
142           5.8          2.7
143           6.8          3.2
144           6.7          3.3
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[150 rows x 2 columns]